// react-message-app/src/App.js
import { useState } from "react";

function App() {
    const [message, setMessage] = useState("Hello World");
    const [input, setInput] = useState("");

    return (
        <div style={{ textAlign: "center", marginTop: "50px" }}>
            <h2>{message}</h2>
            <input
                type="text"
                placeholder="Message to Display"
                onChange={(e) => setInput(e.target.value)}
            />
            <button onClick={() => setMessage(input)}>Display Message</button>
        </div>
    );
}

export default App;

// angular-message-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  message: string = "Hello World";
  inputMessage: string = "";

  updateMessage() {
    this.message = this.inputMessage || "Hello World";
  }
}

<div style="text-align: center; margin-top: 50px;">
  <h2>{{ message }}</h2>
  <input type="text" [(ngModel)]="inputMessage" placeholder="Message to Display">
  <button (click)="updateMessage()">Display Message</button>
</div>

<h1>{{ message }}</h1>  <!-- Test -->
